theme = "catppuccin_latte"

[editor]
cursorline = true
rulers = [88]
text-width = 88
bufferline = "multiple"

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.file-picker]
hidden = false
git-ignore = false
git-global = false

[editor.cursor-shape]
insert = "bar"
