[[language]]
name = "bash"
indent = { tab-width = 2, unit = "  "}
file-types = ["sh", "bash", "bats"]

[language-server.pyright]
# thanks to <https://github.com/helix-editor/helix/discussions/5369#discussioncomment-6113408>
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw","ptl",".pythonstartup",".pythonrc","SConstruct"]
shebangs = ["python"]
roots = ["setup.py", "setup.cfg", "pyproject.toml"]
comment-token = "#"
language-servers = [ "pyright" ]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "json"
formatter = { command = "jq", args = ["--indent", "2"]}

[language-server.vscode-json-language-server]
command = "vscode-json-languageserver"
config = { provideFormatter = true }

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

# [language-server.yaml-language-server.config.yaml.schemas]
# "https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"

# https://docs.deno.com/runtime/getting_started/setup_your_environment/#helix
[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
file-types = ["ts", "tsx"]
auto-format = true
language-servers = ["deno-lsp"]

[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc", "package.json"]
file-types = ["js", "jsx"]
auto-format = true
language-servers = ["deno-lsp"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config.deno.enable = true

# <https://www.roc-lang.org/install#editor-extensions>
# <https://github.com/faldor20/tree-sitter-roc>
[language-server.roc-ls]
command = "roc_language_server"

[[language]]
name = "roc"
scope = "source.roc"
injection-regex = "roc"
file-types = ["roc"]
shebangs = ["roc"]
roots = []
comment-token = "#"
language-servers = ["roc-ls"]
indent = { tab-width = 2, unit = "  " }
auto-format = true
formatter = { command = "roc", args =[ "format", "--stdin", "--stdout"]}

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'

[[grammar]]
name = "roc"
source = { git = "https://github.com/faldor20/tree-sitter-roc.git", rev = "94634c7e882d3c55066aa074cab4911284326deb" }
