[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    "}
file-types = ["sh", "bash", "bats"]

[language-server.pyright]
# thanks to <https://github.com/helix-editor/helix/discussions/5369#discussioncomment-6113408>
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw","ptl",".pythonstartup",".pythonrc","SConstruct"]
shebangs = ["python"]
roots = ["setup.py", "setup.cfg", "pyproject.toml"]
comment-token = "#"
language-servers = [ "pyright" ]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "json"
formatter = { command = "jq", args = ["--indent", "4"]}

[language-server.vscode-json-language-server]
command = "vscode-json-languageserver"
config = { provideFormatter = true }
