# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      # https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#hooks-available
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/rhysd/actionlint
    rev: e7d448ef7507c20fc4c88a95d0c448b848cd6127  # frozen: v1.7.8
    hooks:
      - id: actionlint-system
  - repo: https://github.com/pcrockett/gitleaks
    rev: 0cec2598f76713675989870f0c8343cb4d49614d
    hooks:
      - id: gitleaks-system
  - repo: https://github.com/adrienverge/yamllint
    rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7  # v1.37.1
    hooks:
      - id: yamllint
  - repo: local
    hooks:
      - name: shellcheck
        id: shellcheck
        language: system
        entry: shellcheck
        types: [shell]
      - name: shfmt
        id: shfmt
        language: system
        entry: shfmt
        args: ["--write"]
        types: [shell]
        exclude_types: [csh, tcsh, zsh]
        exclude: rustup-init
      - name: tagref
        id: tagref
        language: system
        entry: tagref
        args: [check]
        pass_filenames: false
      - id: yamlfmt
        name: yamlfmt
        entry: yamlfmt
        language: system
        types:
          - yaml
