# for use with `tw decay` [ref:tw]

uda.decay.type=date
uda.decay.label=Decay Date

uda.decay_coeff.type=string
uda.decay_coeff.label=Decay

urgency.uda.decay_coeff.1.coefficient=1.0
urgency.uda.decay_coeff.2.coefficient=2.0
urgency.uda.decay_coeff.3.coefficient=3.0
urgency.uda.decay_coeff.4.coefficient=4.0
urgency.uda.decay_coeff.5.coefficient=5.0
urgency.uda.decay_coeff.6.coefficient=6.0
urgency.uda.decay_coeff.7.coefficient=7.0
urgency.uda.decay_coeff.8.coefficient=8.0
urgency.uda.decay_coeff.9.coefficient=9.0
urgency.uda.decay_coeff.10.coefficient=10.0
