urgency.user.tag.annoy.coefficient=1          # eliminating minor annoyances
urgency.user.tag.deteriorating.coefficient=3  # things without a deadline, but will get worse the longer i wait
urgency.user.tag.health.coefficient=1         # anything regarding physical, mental, emotional, spiritual health
urgency.user.tag.hindrance.coefficient=4      # eliminating things that slow me down, prevent me from doing something
urgency.user.tag.hobby.coefficient=-4         # for fun, unimportant stuff
urgency.user.tag.loweffort.coefficient=2      # things that can be quickly and easily knocked out
urgency.user.tag.others.coefficient=1         # things that have more impact on others than on me -- my "social responsibility" tag
urgency.user.tag.regular.coefficient=5        # things that need to be done regularly, no matter how unimpactful
urgency.user.tag.risk.coefficient=2           # things that are particularly risky
urgency.user.tag.security.coefficient=2       # for mitigating risk
urgency.user.tag.stress.coefficient=1         # eliminating things that cause stress
urgency.user.tag.unknowns.coefficient=5       # anything that has "unknown unknowns"
