#!/usr/bin/bash
#
# in qtile 0.37.0 a regression was shipped that requires this fix. github issue:
#
#     <https://github.com/qtile/qtile/issues/6023>
#
# eventually when this is fixed, released, and packaged, this script will no longer
# be necessary.
systemctl --user import-environment
exec systemctl --user start --wait qtile.service
